/**
 * `aifn-compute/inference/model`: the model description language on the structured graphs of `aifn-compute/graph/structured`
 * (`model`, `dist`, plates and chains as groups, parameters, deterministic nodes; `expandModel` on `unroll`,
 * `logJoint`, `sampleModel`), discrete factor graphs and their algebra (`discreteFactor`, `factorProduct`,
 * `factorMarginalise`, `factorReduce`) and gates (`gateFactor`), the model's factor graph as a structured graph (`toFactorGraph`), and diagram
 * data (`toPlateDiagram`, `toFactorDiagram`, both `toDiagram` of a structured graph).
 */

export {
  bipartiteGraph,
  discreteFactor,
  discreteFactorGraph,
  factorGraphEdges,
  factorGraphNeighbours,
  factorMarginalise,
  factorProduct,
  factorProductAll,
  factorReduce,
  forEachAssignment,
  gateFactor,
  isTree,
  logPotential,
  normaliseFactor,
  stridesOf,
  tableSize,
  valuesOf,
  variableName,
  type DiscreteFactor,
  type DiscreteFactorGraph,
  type FactorGraphEdge,
} from './factors'
export {
  argRefs,
  argValue,
  cardinalityOf,
  conditionalOf,
  dependencyMaps,
  dist,
  distOf,
  environment,
  evaluateOp,
  expandModel,
  instanceKey,
  instanceLogDensity,
  logJoint,
  model,
  modelMarkovBlanket,
  nestedValues,
  nodeArgs,
  plateChain,
  realise,
  resolveRef,
  sampleModel,
  stochasticParents,
  type Arg,
  type Bindings,
  type DeterministicOp,
  type DistSpec,
  type Env,
  type ExpandedModel,
  type Family,
  type GroupOptions,
  type Instance,
  type Model,
  type ModelBuilder,
  type ModelNode,
  type ModelNodeData,
  type ModelScope,
  type Nested,
  type NodeHandle,
  type NodeOptions,
  type NodeRef,
  type NodeValue,
  type SizeRef,
} from './model'
export {
  factorsOf,
  toDiscreteFactorGraph,
  toFactorDiagram,
  toFactorGraph,
  toPlateDiagram,
  type FactorDiagramOptions,
  type FactorNodeData,
  type ModelDiscreteGraph,
  type ModelFactorGraph,
} from './structure'
export { modelFunctions } from './registry'
