/**
 * `aifn-compute/learning/metrics`: evaluation metrics, each defined once with its registry metadata (as sklearn.metrics):
 * confusion counts, classification rates, curves (ROC, precision–recall, DET, cost, gain), proper scoring rules and
 * calibration, regression errors and deviances, clustering indices, agreement, bootstrap and DeLong intervals, ranking
 * metrics, vector distances, embedding alignment and uniformity, and ordinal metrics; `metricRegistry`, `getMetric`,
 * `listMetrics`. Application metrics (text, detection, quality, generative, fairness, beyond-accuracy) are in
 * `aifn-methods/evaluation`.
 */

export {
  defineMetric,
  isMetric,
  type Capability,
  type Data,
  type InputKind,
  type Label,
  type Labels,
  type Metric,
  type MetricFunction,
  type MetricInfo,
  type MetricSpec,
  type Rows,
} from './core'
export {
  averaged,
  binaryCounts,
  binaryRates,
  confusionMargins,
  confusionMatrix,
  countsAtThreshold,
  oneVsRest,
  perClass,
  tallies,
  type Average,
  type AverageOptions,
  type BinaryCounts,
  type BinaryRates,
  type ConfusionMargins,
  type ConfusionMatrix,
  type ConfusionOptions,
  type CountStatistic,
  type OneVsRestCounts,
  type Tallies,
} from './confusion'
export {
  accuracy,
  balancedAccuracy,
  cohensKappa,
  diagnosticOddsRatio,
  errorRate,
  exactMatch,
  f1,
  fBeta,
  falseNegativeRate,
  falsePositiveRate,
  hammingLoss,
  informedness,
  jaccardScore,
  kappaFromTable,
  markedness,
  matthewsCorrelation,
  negativeLikelihoodRatio,
  negativePredictiveValue,
  positiveLikelihoodRatio,
  precision,
  precisionRecallFscoreSupport,
  recall,
  specificity,
  type ClassificationInput,
  type KappaWeights,
} from './classification'
export {
  auroc,
  averagePrecision,
  binormalAuroc,
  binormalAveragePrecision,
  binormalCurves,
  binormalEqualErrorRate,
  binormalRates,
  costCurve,
  detCurve,
  eer,
  equalErrorRate,
  gainCurve,
  normalisedExpectedCost,
  operatingPoint,
  partialAuroc,
  precisionRecallCurve,
  precisionRecallGainCurve,
  precisionRecallTrapezoid,
  recallAtPrecision,
  rocConvexHull,
  rocCurve,
  specificityAtSensitivity,
  tprAtFpr,
  youdenPoint,
  type AurocOptions,
  type OperatingPoint,
  type PrecisionRecallCurve,
  type RocCurve,
} from './curves'
export {
  brierDecomposition,
  brierScore,
  classwiseCalibrationError,
  confidenceCalibrationError,
  consistencyBars,
  coverage,
  crpsEnsemble,
  crpsGaussian,
  debiasedSquaredCalibrationError,
  expectedCalibrationError,
  gaussianLogScore,
  intervalScore,
  logLoss,
  logScore,
  maximumCalibrationError,
  perplexity,
  pitValues,
  reliabilityDiagram,
  rmsCalibrationError,
  sphericalScore,
  sweepCalibrationError,
  type BinStrategy,
  type BrierDecomposition,
  type GaussianForecast,
  type Interval,
  type PerCase,
  type Probabilities,
  type ReliabilityDiagram,
} from './probabilistic'
export {
  adjustedR2Score,
  explainedVariance,
  gammaDeviance,
  huberLoss,
  logCoshError,
  maxError,
  meanAbsoluteError,
  meanAbsolutePercentageError,
  meanAbsoluteScaledError,
  meanSquaredError,
  meanSquaredLogError,
  medianAbsoluteError,
  normalisedRootMeanSquaredError,
  pinballLoss,
  poissonDeviance,
  r2Score,
  rootMeanSquaredError,
  rootMeanSquaredScaledError,
  symmetricMeanAbsolutePercentageError,
  tweedieDeviance,
  tweedieUnitDeviance,
  weightedMeanAbsolutePercentageError,
  type RegressionOptions,
  type ScaledErrorOptions,
} from './regression'
export {
  dcg,
  gainFunction,
  positionDiscount,
  expectedReciprocalRank,
  hitRate,
  meanAveragePrecision,
  meanReciprocalRank,
  ndcg,
  precisionAtK,
  rPrecision,
  recallAtK,
  type AtKOptions,
  type DcgOptions,
  type Gain,
  type RankingInput,
  type AveragePrecisionOptions,
  type RecallOptions,
} from './ranking'
export {
  adjustedMutualInformation,
  adjustedRandIndex,
  calinskiHarabasz,
  completeness,
  contingencyTable,
  daviesBouldin,
  dunnIndex,
  fowlkesMallows,
  homogeneity,
  homogeneityCompletenessV,
  mutualInformationScore,
  normalisedMutualInformation,
  pairConfusion,
  randIndex,
  silhouetteSamples,
  silhouetteScore,
  vMeasure,
  variationOfInformation,
  type Contingency,
  type EntropyMean,
} from './clustering'
export {
  chiSquareStatistic,
  concordanceCorrelation,
  contingencyCoefficient,
  cramersV,
  fleissKappa,
  intraclassCorrelation,
  kendallCorrelation,
  krippendorffAlpha,
  pearsonCorrelation,
  spearmanCorrelation,
  theilsU,
  tschuprowT,
  type IccForm,
  type MeasurementLevel,
} from './agreement'
export {
  angularDistance,
  chebyshevDistance,
  cosineDistance,
  cosineSimilarity,
  euclideanDistance,
  hausdorffDistance,
  hausdorffDistances,
  mahalanobisDistance,
  manhattanDistance,
  minkowskiDistance,
  orthogonalProcrustes,
  procrustesDisparity,
  type HausdorffDistances,
  type Procrustes,
} from './distances'
export { alignment, uniformity, type AlignmentOptions, type UniformityOptions } from './representation'
export {
  aurocDeLong,
  bootstrapMetric,
  delongTest,
  pairedBootstrap,
  waldInterval,
  wilsonInterval,
  type BootstrapOptions,
  type Cases,
  type MetricBootstrap,
} from './uncertainty'
export { getMetric, isBetter, listMetrics, metricRegistry } from './registry'
export {
  ordinalMeanAbsoluteError,
  macroMeanAbsoluteError,
  withinToleranceAccuracy,
  quadraticWeightedKappa,
  rankedProbabilityScore,
  ordinalConcordanceIndex,
} from './ordinal'

// Helpers for defining metrics outside this module (the application metrics of `aifn-methods/evaluation`): the input
// conventions every metric here follows.
export {
  classesOf,
  compareLabels,
  dense as denseMatrix,
  divide,
  encodeLabels,
  isMatrixLike,
  labelList,
  matrix,
  positiveOf,
  sameLength,
  values as metricValues,
  type Dense,
} from './core'
export { metricsFunctions } from './function-registry'
