/**
 * Elliptic, Bessel and Parks–McClellan designs and the smoothing filters against scipy (fixture `signal/filters`,
 * generated by `gen/signal/filters.py`), plus the laws they satisfy.
 */
import { describe, expect, it } from 'vitest'
import {
  bessel,
  ellip,
  freqz,
  matchedFilter,
  medfilt,
  remez,
  savgolCoeffs,
  savgolFilter,
  wiener,
  wienerDenoise,
} from 'aifn-compute/signal/filters'
import { ellipj, ellipkm1 } from 'aifn-compute/numerics/special'
import { toTransferFunction, toZerosPolesGain } from 'aifn-compute/systems'
import { complexAbs, toComplexFlat, toFlat, type Tensor } from 'aifn-compute/foundation/tensor'
import { close } from '../helpers'
import { fixture } from '../../fixtures'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const F = fixture<any>('signal/filters')
type Band = 'lowpass' | 'highpass' | 'bandpass' | 'bandstop'
const sorted = (t: Tensor) => {
  const v = toComplexFlat(t).sort((a, b) => a.re - b.re || a.im - b.im)
  return { re: v.map((z) => z.re), im: v.map((z) => z.im) }
}
const wn = (w: number | number[]) => (typeof w === 'number' ? w : ([w[0], w[1]] as const))

describe('elliptic functions against scipy.special', () => {
  it('ellipj and ellipkm1, and the identities sn² + cn² = 1, dn² + m sn² = 1', () => {
    for (const c of F.ellipj) {
      const j = ellipj(c.u, c.m)
      close([j.sn, j.cn, j.dn, j.ph], [c.sn, c.cn, c.dn, c.ph], 1e-12)
      expect(j.sn ** 2 + j.cn ** 2).toBeCloseTo(1, 14)
      expect(j.dn ** 2 + c.m * j.sn ** 2).toBeCloseTo(1, 13)
    }
    for (const c of F.ellipkm1) expect(Math.abs(ellipkm1(c.p) - c.y) / c.y).toBeLessThan(1e-14)
  })
})

describe('IIR designs against scipy.signal', () => {
  it('ellip: zeros, poles and gain in every band type', () => {
    for (const c of F.ellip) {
      const s = toZerosPolesGain(ellip(c.n, c.rp, c.rs, wn(c.wn), { btype: c.btype as Band })).repr
      const z = sorted(s.zeros)
      const p = sorted(s.poles)
      close(z.re, c.z.re, 1e-10)
      close(z.im, c.z.im, 1e-10)
      close(p.re, c.p.re, 1e-10)
      close(p.im, c.p.im, 1e-10)
      expect(Math.abs(s.gain - c.k) / Math.abs(c.k)).toBeLessThan(1e-10)
    }
  })

  it('ellip: an equiripple passband within rp and a stopband at least rs down', () => {
    const h = freqz(ellip(6, 0.5, 50, 0.3), { n: 4096 })
    const f = toFlat(h.f)
    const db = toFlat(complexAbs(h.values) as Tensor).map((v) => 20 * Math.log10(v))
    f.forEach((fv, i) => {
      if (fv < 0.15 * 0.98) {
        expect(db[i]).toBeLessThanOrEqual(1e-9)
        expect(db[i]).toBeGreaterThanOrEqual(-0.5 - 1e-9)
      }
      if (fv > 0.2) expect(db[i]).toBeLessThanOrEqual(-50 + 1e-6)
    })
  })

  it('bessel (phase-normalised) transfer functions', () => {
    for (const c of F.bessel) {
      const tf = toTransferFunction(bessel(c.n, wn(c.wn), { btype: c.btype as Band })).repr
      close(tf.b, c.b, 1e-10)
      close(tf.a, c.a, 1e-10)
    }
  })
})

describe('remez against scipy.signal.remez', () => {
  it('type I and II low-pass (weighted), band-pass and high-pass; linear phase', () => {
    for (const c of F.remez) {
      const s = remez(c.numtaps, c.bands, c.desired, c.weight ? { weight: c.weight } : {})
      const h = toFlat(toTransferFunction(s).repr.b)
      close(h, c.h, 1e-9)
      h.forEach((v, i) => expect(v).toBeCloseTo(h[h.length - 1 - i], 12))
      expect(s.extremals.shape[0]).toBe(Math.floor((c.numtaps + 1) / 2) + 1)
    }
  })
})

describe('smoothing against scipy.signal', () => {
  it('savgol_filter in each mode, derivatives, and savgol_coeffs', () => {
    for (const c of F.savgol)
      close(toFlat(savgolFilter(F.x, c.window, c.order, { deriv: c.deriv, mode: c.mode }).data), c.y, 1e-11)
    for (const c of F.savgolCoeffs) close(toFlat(savgolCoeffs(c.window, c.order, { deriv: c.deriv })), c.h, 1e-12)
    // A polynomial of degree ≤ polyorder passes through unchanged.
    const q = Array.from({ length: 15 }, (_, i) => 0.3 * i * i - i + 2)
    close(toFlat(savgolFilter(q, 5, 2).data), q, 1e-12)
  })

  it('medfilt and wiener', () => {
    for (const c of F.medfilt) close(toFlat(medfilt(F.x, c.k).data), c.y, 1e-15)
    for (const c of F.wiener)
      close(toFlat(wiener(F.x, c.size, c.noise === null ? {} : { noise: c.noise }).data), c.y, 1e-12)
  })

  it('wienerDenoise passes a clean signal as σ² → 0 and keeps only bins above the noise', () => {
    const n = 256
    const s = Array.from({ length: n }, (_, i) => Math.sin((2 * Math.PI * 8 * i) / n))
    close(toFlat(wienerDenoise(s, 0).signal.data), s, 1e-12)
    const g = toFlat(wienerDenoise(s, 0.01).gain)
    expect(g[8]).toBeGreaterThan(0.99)
    expect(g[60]).toBe(0)
  })

  it('matchedFilter finds a buried template; the normalised score is a correlation', () => {
    const t = [1, -1, 1, 1, -1, 1, -1, -1]
    const x = Array.from({ length: 100 }, (_, i) => 0.3 * Math.sin(i * 1.7))
    t.forEach((v, k) => (x[40 + k] += v))
    expect(matchedFilter(x, t).peak.index).toBe(40)
    const m = matchedFilter(x, t, { normalized: true })
    expect(m.peak.index).toBe(40)
    expect(m.peak.value).toBeLessThanOrEqual(1)
  })
})

describe('group delay of a zeros–poles–gain system', () => {
  it('agrees with the transfer-function route', async () => {
    const { groupDelay, butter } = await import('aifn-compute/signal/filters')
    const zpk = butter(5, 0.3)
    const tf = butter(5, 0.3, { output: 'tf' })
    close(toFlat(groupDelay(zpk, { n: 64 }).delay), toFlat(groupDelay(tf, { n: 64 }).delay), 1e-8)
  })
})
