/**
 * The Fourier transforms of `aifn-compute/foundation/fourier` against numpy.fft and scipy.fft (fixture `signal`, generated by
 * `fixtures/gen/signal.py`), on complex128 tensors.
 */
import { describe, expect, it } from 'vitest'
import {
  dct,
  dft,
  fft,
  fft2,
  fftfreq,
  fftshift,
  ifft,
  ifftshift,
  irfft,
  rfft,
  rfftfreq,
} from 'aifn-compute/foundation/fourier'
import {
  complex,
  fromData,
  imagPart,
  realPart,
  tensor,
  toFlat,
  type Tensor,
  type Value,
} from 'aifn-compute/foundation/tensor'
import { fixture } from '../../fixtures'

type Cx = { re: number[] | number[][]; im: number[] | number[][] }
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const F = fixture<any>('signal')

function close(actual: Value, expected: number[] | number[][], tol = 1e-10) {
  const a = toFlat(actual as Tensor)
  const e = (expected as number[]).flat() as number[]
  expect(a.length).toBe(e.length)
  const scale = Math.max(1, ...e.map(Math.abs))
  let worst = 0
  for (let i = 0; i < a.length; i++) worst = Math.max(worst, Math.abs(a[i] - e[i]))
  expect(worst / scale).toBeLessThan(tol)
}
function closeC(actual: Value, expected: Cx, tol = 1e-10) {
  expect((actual as Tensor).dtype).toBe('complex128')
  close(realPart(actual), expected.re, tol)
  close(imagPart(actual), expected.im, tol)
}
const cxIn = (c: Cx): Tensor => complex(tensor((c.re as number[]).flat()), tensor((c.im as number[]).flat())) as Tensor

describe('Fourier transforms against numpy', () => {
  it('fft and ifft of any length (radix-2 and Bluestein), with padding', () => {
    for (const c of F.fft) {
      const x = cxIn(c.x)
      const n = (c.x.re as number[]).length
      closeC(fft(x), c.fft, 1e-11)
      closeC(ifft(x), c.ifft, 1e-11)
      closeC(fft(x, { n: n + 5 }), c.fft_pad, 1e-11)
    }
  })

  it('dft agrees with fft', () => {
    const c = F.fft[4]
    closeC(dft(cxIn(c.x)), c.fft, 1e-10)
  })

  it('rfft, irfft, frequencies and shifts', () => {
    const r = F.rfft
    closeC(rfft(r.x as number[]), r.rfft)
    closeC(rfft(r.x as number[], { n: 16 }), r.rfft16)
    close(irfft(rfft(tensor(r.x)), { n: 9 }), r.irfft)
    close(fftfreq(9, 0.1), r.fftfreq)
    close(rfftfreq(10, 0.1), r.rfftfreq)
    const x = [0, 1, 2, 3, 4]
    expect(toFlat(fftshift(x))).toEqual([3, 4, 0, 1, 2])
    expect(toFlat(ifftshift(fftshift(x)))).toEqual(x)
  })

  it('fft2 matches numpy', () => {
    const rows = F.fft2.x as number[][]
    closeC(fft2(fromData(Float64Array.from(rows.flat()), [5, 6])), F.fft2.fft2)
  })

  it('dct matches scipy (type II, orthonormal) along the last axis', () => {
    const m = F.dct.x as number[][]
    close(dct(fromData(Float64Array.from(m.flat()), [3, 8])), F.dct.dct, 1e-12)
  })
})
