/**
 * The convolutions and the linear filter of `aifn-compute/foundation/convolution` against scipy.signal and scipy.ndimage
 * (fixture `signal`, generated by `fixtures/gen/signal.py`).
 */
import { describe, expect, it } from 'vitest'
import {
  convolve,
  convolve2d,
  correlate,
  correlate2d,
  correlationLags,
  fftConvolve,
  linearFilter,
} from 'aifn-compute/foundation/convolution'
import { fromData, tensor, toFlat, type Tensor, type Value } from 'aifn-compute/foundation/tensor'
import { fixture } from '../../fixtures'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const F = fixture<any>('signal')

function close(actual: Value, expected: number[] | number[][], tol = 1e-10) {
  const a = toFlat(actual as Tensor)
  const e = (expected as number[]).flat() as number[]
  expect(a.length).toBe(e.length)
  const scale = Math.max(1, ...e.map(Math.abs))
  let worst = 0
  for (let i = 0; i < a.length; i++) worst = Math.max(worst, Math.abs(a[i] - e[i]))
  expect(worst / scale).toBeLessThan(tol)
}

describe('convolution and correlation', () => {
  const C = F.convolution
  it.each(['full', 'same', 'valid'] as const)('%s mode, direct and FFT, with lags', (mode) => {
    close(convolve(C.u, C.v, { mode }), C[`convolve-${mode}`], 1e-12)
    close(convolve(C.u, C.v, { mode, method: 'fft' }), C[`convolve-${mode}`], 1e-12)
    close(correlate(C.u, C.v, { mode }), C[`correlate-${mode}`], 1e-12)
    expect(toFlat(correlationLags(9, 4, mode))).toEqual(C[`lags-${mode}`])
    expect(toFlat(correlationLags(4, 9, mode))).toEqual(C[`lags-swap-${mode}`])
  })

  it('long inputs take the FFT path', () => {
    close(fftConvolve(C.long.u, C.long.v), C.long.full, 1e-12)
    close(convolve(C.long.u, C.long.v), C.long.full, 1e-12)
  })
})

describe('linearFilter', () => {
  it('matches scipy lfilter, with and without an initial state', () => {
    const f = F.filtering
    close(linearFilter(f.b, f.a, tensor(f.x)), f.lfilter, 1e-10)
    const zi = tensor((f.zi as number[]).map((z) => z * f.x[0]))
    close(linearFilter(f.b, f.a, tensor(f.x), { zi }), f.lfilterZi.y, 1e-10)
  })

  it('an FIR filter is a convolution', () => {
    const x = tensor([1, -2, 3, 0.5, 4])
    close(linearFilter([0.5, 0.25], [1], x), toFlat(convolve(x, [0.5, 0.25])).slice(0, 5), 1e-15)
  })
})

describe('image operators against scipy.ndimage', () => {
  const I = F.image
  const img = fromData(Float64Array.from((I.image as number[][]).flat()), [12, 10])
  it.each(['reflect', 'mirror', 'nearest', 'constant', 'wrap'] as const)('correlate2d with %s borders', (border) => {
    close(correlate2d(img, I.kernel, { border }), I[`correlate-${border}`], 1e-12)
  })
  it('convolve2d', () => {
    close(convolve2d(img, I.kernel), I.convolve, 1e-12)
  })
})
